### ISSUE TITLE
Create regex for scanning

### ISSUE THREAD

**Issue by infernobox** [assenavmai/Compilers#1]
Just have the regex going, have a main in the '.l' file and output what is being scanned from testfiles

**Comment by infernobox** [comment]
This is what you have been working on yes?

**Comment by infernobox** [comment]
I am going to code this also, just to get my head in the right place for this project

**Comment by jkandloosi** [comment]
yes, but from what i understand, this is very simple since all i need to do is place the correct kind of tokens needed in the spec - it's not like the warmup where we had to ensure patterns like hyphanated and apostrophised words

**Comment by infernobox** [comment]
You are right. So this is truly easy.
I am going to correct a dummy scanner to connect the parser up so we can start on the grammars
