### ISSUE TITLE
Create file structure in cm.y file to start filling up

### ISSUE THREAD

**Issue by infernobox** [assenavmai/Compilers#4]

**Comment by jkandloosi** [comment]
when you say file structure, do you mean the setup of the grammar or something else?

**Comment by infernobox** [comment]
set up of the grammars, just like one pushed to git so then we both can work from there. So we have the same file format. Then we can split up the grammars from there? I can do this one if you like. 

I just committed my dummy scanner to the scanner branch btw

**Comment by jkandloosi** [comment]
no that's fine, i can work on this one too. thanks for clarifying
